# Generated by Django 3.0.10 on 2020-09-19 15:41

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('price', models.FloatField(verbose_name='Price')),
                ('tax', models.FloatField(verbose_name='Tax')),
                ('paid', models.BooleanField(default=False, verbose_name='Is payment recieved for Booking?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Hall Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Movie Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Movie Description')),
                ('length', models.FloatField(verbose_name='Movie Lenght')),
                ('cast', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('director', models.CharField(max_length=100, verbose_name='Movie Director')),
                ('genre', models.CharField(blank=True, choices=[('THRILLER', 'Thriller'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('ADVENTURE', 'Adventure'), ('SCI_FI', 'Sci-Fi'), ('ROMANCE', 'Romance'), ('ANIMATION', 'Animation'), ('FANTASY', 'Fantasy'), ('CRIME', 'Crime'), ('MYSTERY', 'Mystery'), ('SUPERHERO', 'Superhero')], default='', max_length=100, null=True, verbose_name='Genre of Movie')),
                ('release_date', models.DateField(default=datetime.date(2020, 9, 19), verbose_name='Movie Release Date')),
                ('certificate', models.CharField(choices=[('A', 'A'), ('UA', 'U/A'), ('U', 'U'), ('S', 'S')], max_length=100, verbose_name='Certificate of Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('row', models.CharField(max_length=100, verbose_name='Seat Row')),
                ('column', models.CharField(max_length=100, verbose_name='Seat Column')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.Hall', verbose_name='Hall')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('base_price', models.FloatField(verbose_name='Price Multiplier')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='bookings.Hall', verbose_name='Hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='bookings.Movie', verbose_name='Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Theatre Name')),
                ('city', models.CharField(max_length=100, verbose_name='Theatre City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('price', models.FloatField(verbose_name='Price')),
                ('booking', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='bookings.Booking', verbose_name='Booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.Seat', verbose_name='Seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.Show', verbose_name='Show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Seat Type Name')),
                ('price_multiplier', models.FloatField(verbose_name='Price Multiplier')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_types', to='bookings.Theatre', verbose_name='Theatre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.SeatType', verbose_name='Seat Type'),
        ),
        migrations.AddField(
            model_name='hall',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='bookings.Theatre', verbose_name='Theatre'),
        ),
    ]
