# Generated by Django 3.0.10 on 2020-09-20 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date(2020, 9, 20), verbose_name='Movie Release Date'),
        ),
    ]
