# Generated by Django 3.0.10 on 2020-09-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200921_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tax',
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
